In [5]:
%reload_ext autoreload
%autoreload 2

import os
import sys
import numpy as np
from timeit import default_timer as timer
from _collections import OrderedDict
import shutil
from pprint import pprint
start = timer()
HOME = os.path.expanduser("~")
PATH = os.path.join(HOME, 'programming/pipeline_utility')
sys.path.append(PATH)
from utilities.file_location import FileLocationManager
from utilities.sqlcontroller import SqlController
from utilities.utilities_cvat_neuroglancer import get_structure_number, NumpyToNeuroglancer, get_segment_properties
from utilities.utilities_affine import align_point_sets, align_atlas, DK52_centers


In [2]:
animal = 'DK52'
fileLocationManager = FileLocationManager(animal)
OUTPUT_DIR = os.path.join(fileLocationManager.neuroglancer_data, 'atlas')

In [3]:
sql_controller = SqlController(animal)
thumbnail_dir = os.path.join(fileLocationManager.prep, 'CH1', 'thumbnail_aligned')

print(f'resolution: {sql_controller.scan_run.resolution}')
print(f'width: {sql_controller.scan_run.width}')
print(f'height: {sql_controller.scan_run.height}')
box_w = sql_controller.scan_run.width * sql_controller.scan_run.resolution / 10  # 10 mum scale
box_h = sql_controller.scan_run.height * sql_controller.scan_run.resolution / 10  # 10 mum scale
box_z = len(os.listdir(thumbnail_dir))  # 20 mum scale
box_center = np.array([box_w, box_h, box_z]) / 2

atlasV7_volume = np.zeros((int(box_h), int(box_w), int(box_z)), dtype=np.uint8)
print('Shape of atlas volume', atlasV7_volume.shape)


resolution: 0.325
width: 65000
height: 36000
Shape of atlas volume (1170, 2112, 486)


In [10]:
align_atlas(DK52_centers, atlas_box_size=(2112, 1170, 486))

Please type the following numbers into neuroglancer to align the atlas structures.

Rotation:
[[ 0.99539957  0.36001948  0.01398446]
 [-0.35951649  0.99520404 -0.03076857]
 [-0.02361111  0.02418234  1.05805842]]

Translation:
[[ 1135.64220169]
 [13549.03252152]
 [  -14.68028224]]


(array([[ 0.99539957,  0.36001948,  0.01398446],
        [-0.35951649,  0.99520404, -0.03076857],
        [-0.02361111,  0.02418234,  1.05805842]]),
 array([[ 369.08371555],
        [4403.43556949],
        [-293.60564487]]))

In [ ]:
pp = list(source_centers.values())
x = np.array([(p[0][0],p[0][1],p[0][2]) for p in pp])