In [1]:
from pipeline.utilities.utilities_bioformats import get_czi_metadata, get_fullres_series_indices

infile = '/net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK77-DUANE/czi/DK77_slide001_2022_01_25_axion2.czi'
metadata = get_czi_metadata(infile)
metadata

{0: {'width': 14887,
  'height': 9387,
  'channels': 1,
  'resolution': 0.325,
  'acquisition_date': '2022-01-26T02:41:32.632'},
 1: {'width': 7443,
  'height': 4693,
  'channels': 1,
  'resolution': 0.325,
  'acquisition_date': '2022-01-26T02:41:32.632'},
 2: {'width': 3721,
  'height': 2346,
  'channels': 1,
  'resolution': 0.325,
  'acquisition_date': '2022-01-26T02:41:32.632'},
 3: {'width': 1860,
  'height': 1173,
  'channels': 1,
  'resolution': 0.325,
  'acquisition_date': '2022-01-26T02:41:32.632'},
 4: {'width': 930,
  'height': 586,
  'channels': 1,
  'resolution': 0.325,
  'acquisition_date': '2022-01-26T02:41:32.632'},
 5: {'width': 13053,
  'height': 9391,
  'channels': 1,
  'resolution': 0.325,
  'acquisition_date': '2022-01-26T02:41:32.632'},
 6: {'width': 6526,
  'height': 4695,
  'channels': 1,
  'resolution': 0.325,
  'acquisition_date': '2022-01-26T02:41:32.632'},
 7: {'width': 3263,
  'height': 2347,
  'channels': 1,
  'resolution': 0.325,
  'acquisition_date': '202

In [4]:
from datetime import datetime
timestamp = metadata[0]['acquisition_date']
new =timestamp.split('T')[0]
new

'2022-01-26'

In [11]:
from aicsimageio import AICSImage

# Get an AICSImage object
img = AICSImage("/net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK77-DUANE/czi/DK77_slide186_2022_02_07_axion2.czi")  # selects the first scene found
img.data  # returns 5D TCZYX numpy array
img.xarray_data  # returns 5D TCZYX xarray data array backed by numpy
img.dims  # returns a Dimensions object
img.dims.order  # returns string "TCZYX"
img.dims.X  # returns size of X dimension
img.shape  # returns tuple of dimension sizes in TCZYX order
img.get_image_data("CZYX", T=0)  # returns 4D CZYX numpy array

# Get the id of the current operating scene
print("CURRENT SCENE: ", img.current_scene)

# Get a list valid scene ids
#img.scenes

# Change scene using name
#img.set_scene("Image:1")
# Or by scene index
#img.set_scene(1)


CURRENT SCENE:  ScanRegion0


In [17]:
print(img.shape)
print(img.physical_pixel_sizes.X, img.physical_pixel_sizes.Y, img.physical_pixel_sizes.Z )

# img.channel_names  # returns a list of string channel names found in the metadata
# img.physical_pixel_sizes.Z  # returns the Z dimension pixel size as found in the metadata
# img.physical_pixel_sizes.Y  # returns the Y dimension pixel size as found in the metadata
# img.physical_pixel_sizes.X  # returns the X dimension pixel size as found in the metadata
#AICSImage("/net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK77-DUANE/czi/DK77_slide186_2022_02_07_axion2.czi").save("my_file.ome.png")


(1, 1, 1, 11215, 9390)
0.325 0.325 None


In [5]:
import slideio
slide = slideio.open_slide("/net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK77-DUANE/czi/DK77_slide186_2022_02_07_axion2.czi", "CZI")
num_scenes = slide.num_scenes
scene = slide.get_scene(0)
print(num_scenes, scene.name, scene.rect, scene.num_channels)

4 (s:0 i:0 v:0 h:0 r:0 b:0) (-143208, 29368, 9390, 11215) 1


In [27]:
from aicsimageio import AICSImage

img = AICSImage("/net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK77-DUANE/czi/DK77_slide186_2022_02_07_axion2.czi")  # selects the first scene found

#print(img.data)
#print(img.shape)
print(img.get_image_data("CZYX", S=0, T=0))
#print("CURRENT SCENE: ", img.current_scene)
#print("CURRENT SCENE INDEX: ", img.current_scene_index)
print("scenes", img.get_image_dask_data)


[[[[0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   ...
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]
   [0 0 0 ... 0 0 0]]]]
scenes <bound method AICSImage.get_image_dask_data of <AICSImage [Reader: CziReader, Image-is-in-Memory: True]>>


In [26]:
from aicsimageio import AICSImage
from sys import getsizeof
aics_img = AICSImage("/net/birdstore/Active_Atlas_Data/data_root/pipeline_data/DK77-DUANE/czi/DK77_slide186_2022_02_07_axion2.czi")
#aics_img.dask_data
aics_img.current_scene
getsizeof(aics_img)
aics_img.save("test1.png")

/usr/local/share/pipeline/lib/python3.8/site-packages/ome_types/_convenience.py:105: FutureWarning: The default XML parser will be changing from 'xmlschema' to 'lxml' in version 0.4.0.  To silence this warning, please provide the `parser` argument, specifying either 'lxml' (to opt into the new behavior), or'xmlschema' (to retain the old behavior).
  d = to_dict(os.fspath(xml), parser=parser, validate=validate)
