In [1]:
import sys
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import plotly.express as px
import numpy as np
import cv2
from superpose3d import Superpose3D

PIPELINE_ROOT = Path('../src').resolve().parent.parent
sys.path.append(PIPELINE_ROOT.as_posix())
print(PIPELINE_ROOT)

from library.registration.brain_structure_manager import BrainStructureManager
from library.registration.algorithm import umeyama

/home/eddyod/programming/preprocessing-pipeline/src


In [2]:
def brain_to_atlas_transform(brain_coord, r, t):
    brain_coord = np.array(brain_coord).reshape(3, 1) # Convert to a column vector
    atlas_coord = r @ brain_coord + t
    return atlas_coord.T[0] # Convert back to a row vector

def calculate_distance(com1, com2):
    return (np.linalg.norm(com1 - com2))
        
def plot_point_sets_3d(point_sets):
    df = pd.DataFrame()
    for data, label in point_sets:
        df_cur = pd.DataFrame(data.T, columns=['x', 'y', 'z'])
        df_cur['label'] = label
        #df = df.concat(df_cur, ignore_index=True)
        df = pd.concat([df, df_cur], axis= 0)
    
    fig = px.scatter_3d(df, x='x', y='y', z='z', color='label', width=800, height=600)
    fig.update_layout(
    scene={
        'xaxis': {'range': (0, 528)}, 
        'yaxis': {'range': (0, 320)},
        'zaxis': {'range': (0, 456)},
    })
    return fig
        

In [3]:
animal = 'Atlas'
brain = BrainStructureManager(animal)
brain.fixed_brain = BrainStructureManager('Allen')

In [ ]:
brainstem_keys = set(brain.allen_structures_keys) - brain.midbrain_keys 

In [4]:
moving_coms = brain.get_coms(annotator_id=1)
allen_coms = brain.fixed_brain.get_coms(annotator_id=1)
common_keys = sorted(allen_coms.keys() & moving_coms.keys() & brain.midbrain_keys)
allen_points = np.array([allen_coms[s] for s in common_keys])
moving_points = np.array([moving_coms[s] for s in common_keys])

In [13]:
common_keys

['3N_L',
 '3N_R',
 '4N_L',
 '4N_R',
 'IC',
 'PBG_L',
 'PBG_R',
 'SC',
 'SNC_L',
 'SNC_R',
 'SNR_L',
 'SNR_R']

In [ ]:
common_midbrain_keys = sorted(allen_coms.keys() & moving_coms.keys() & brain.midbrain_keys)
allen_midbrain_points = np.array([allen_coms[s] for s in common_midbrain_keys])
moving_midbrain_points = np.array([moving_coms[s] for s in common_midbrain_keys])

In [5]:
allen_point_dict = {s:allen_coms[s] for s in common_keys}
moving_point_dict = {s:moving_coms[s] for s in common_keys}

In [6]:
len(moving_point_dict)

12

In [7]:
distances = []
sortme = {}
for structure in common_keys:
    (x,y,z) = allen_point_dict[structure]
    allen_point = np.array([x,y,z])    
    moving_point = np.array(moving_point_dict[structure])
    #print(atlas_point, allen_point)
    d = calculate_distance(allen_point, moving_point)
    distances.append(d)
    sortme[structure] = d
print(f'n={len(distances)}, min={min(distances)} max={max(distances)}, mean={np.mean(distances)}')
ds = {k: v for k, v in sorted(sortme.items(), key=lambda item: item[1])}
for structure, d in ds.items():
    print(f'{structure} distance from Allen={round(d,2)} micrometers')

n=12, min=721.4915928131109 max=1098.0319691156537, mean=946.013322070747
SNC_R distance from Allen=721.49 micrometers
SNC_L distance from Allen=793.62 micrometers
PBG_L distance from Allen=829.22 micrometers
SNR_L distance from Allen=874.38 micrometers
SNR_R distance from Allen=937.88 micrometers
IC distance from Allen=940.53 micrometers
PBG_R distance from Allen=977.88 micrometers
SC distance from Allen=1016.55 micrometers
3N_L distance from Allen=1035.79 micrometers
4N_L distance from Allen=1049.88 micrometers
4N_R distance from Allen=1076.9 micrometers
3N_R distance from Allen=1098.03 micrometers


In [ ]:
plot_point_sets_3d([
    (moving_points.T/25, 'unaligned moving centers'),
    (allen_points.T/25, 'Allen centers')
])

In [ ]:
(RMSD, R1, t1, _) = Superpose3D(allen_points, moving_points, allow_rescale=True)
t1 = t1.reshape(3,1)
print(RMSD)
print(R1)
print(t1)

In [ ]:
allen_midbrain_points.shape

In [14]:
R, t = umeyama(moving_points.T, allen_points.T)

In [15]:
t

array([[-1763.99609251],
       [ -994.38034956],
       [  202.30461861]])

In [16]:
reg_points = R @ moving_points.T + t

 That does not preclude starting the new idea but is just to say that somehow we need to get David's attention on what you have done- do a graph
= box plot of the midbrain com distances vs allen (active atlas based)
=box plot of the brainstem vs allen distances (but not using midbrain values to improve the distances)
This should provide an easy visual...


When the tethering is done for the brainstem structures though- he does not want the midbrain metrics to be included ( I don't know though if he means that the alignment is done with midbrain and then the evaluated outputs are only for the brainstem structures...?) your guess is best
So- in any case it was clear that he did not want metrics for midbrain and brainstem structures to be combined.

In [17]:
print('Mean')
print(np.mean(allen_points, axis=0))
print(np.mean(reg_points, axis=1))
print('Min')
print(np.min(allen_points, axis=0))
print(np.min(reg_points, axis=1))
print('Max')
print(np.max(allen_points, axis=0))
print(np.max(reg_points, axis=1))

Mean
[9109.68666667 4010.52333333 5691.12833333]
[9109.68666667 4010.52333333 5691.12833333]
Min
[8354.09 2325.   3551.05]
[8228.68088835 2264.45040905 3525.33562864]
Max
[10400.    5167.29  7833.27]
[10366.46591136  5030.31025861  7835.449059  ]


In [12]:
distances = []
sortme = {}
for structure in common_keys:
    (x,y,z) = allen_point_dict[structure]
    allen_point = np.array([x,y,z])    
    moving_point = np.array(moving_point_dict[structure])
    reg_point = brain_to_atlas_transform(moving_point, R, t)
    d = calculate_distance(allen_point, reg_point)
    distances.append(d)
    #print(f'{structure} COM={reg_point.round()} distance={round(d,2)}')
    sortme[structure] = d

print(f'n={len(distances)}, min={min(distances)} max={max(distances)}, mean={np.mean(distances)}')
ds = {k: v for k, v in sorted(sortme.items(), key=lambda item: item[1])}
for structure, d in ds.items():
    print(f'{structure} {round(d,2)}')

n=12, min=98.58314289126439 max=261.7483262163751, mean=196.5790116749173
IC 98.58
PBG_R 122.35
PBG_L 176.88
SNR_R 178.23
SC 178.82
4N_L 194.27
3N_L 203.74
4N_R 223.61
3N_R 234.29
SNC_L 237.07
SNR_L 249.37
SNC_R 261.75


In [ ]:
# all n=37, min=57.787495718601974 max=732.1160732177623, mean=307.6266899370127

In [ ]:
plot_point_sets_3d([
    (reg_points/25, 'registered moving centers'),
    (allen_points.T/25, 'Allen centers')    
])