In [5]:
import sys
sys.path.append('/home/zhw272/programming/pipeline_utility')
from notebooks.Will.demons_assessment_brain_to_atlas import get_demons_transform
import numpy as np

In [2]:
prepi = 'DK39'
demons_transform = get_demons_transform(prepi)


In [3]:
print(demons_transform)


itk::simple::Transform
 GaussianSmoothingOnUpdateDisplacementFieldTransform (0x204b150)
   RTTI typeinfo:   itk::GaussianSmoothingOnUpdateDisplacementFieldTransform<double, 3u>
   Reference Count: 1
   Modified Time: 682
   Debug: Off
   Object Name: 
   Observers: 
     none
   DisplacementField: 
     Image (0x21d52a0)
       RTTI typeinfo:   itk::Image<itk::Vector<double, 3u>, 3u>
       Reference Count: 3
       Modified Time: 679
       Debug: Off
       Object Name: 
       Observers: 
         none
       Source: (none)
       Source output name: (none)
       Release Data: Off
       Data Released: False
       Global Release Data: Off
       PipelineMTime: 0
       UpdateMTime: 0
       RealTimeStamp: 0 seconds 
       LargestPossibleRegion: 
         Dimension: 3
         Index: [0, 0, 0]
         Size: [435, 262, 117]
       BufferedRegion: 
         Dimension: 3
         Index: [0, 0, 0]
         Size: [435, 262, 117]
       RequestedRegion: 
         Dimension: 3
         

In [41]:
origin = np.array([31.2,26,40])
scale = np. array([41.6, 41.6, 80])
size = np.array([435, 262, 117])

In [42]:
point = origin + np.array([1,1,1])
transformed_point = demons_transform.TransformPoint(point)
print(transformed_point-point)

[6.22216194e-06 1.62031151e-06 7.06197739e-07]


In [44]:
point = origin + np.array([0.5,0.5,0.5])
transformed_point = demons_transform.TransformPoint(point)
print(transformed_point-point)

[7.77770243e-07 2.02538939e-07 8.82747173e-08]


In [45]:
point = origin + scale*size-np.array([1,1,1])
transformed_point = demons_transform.TransformPoint(point)
print(transformed_point-point)

[0. 0. 0.]


In [47]:
point = origin+scale*size-np.array([1,1,1])
transformed_point = demons_transform.TransformPoint(point)
print(transformed_point-point)

[0. 0. 0.]


In [48]:
point

array([18126.2, 10924.2,  9399. ])

In [66]:
pointi  = origin + np.array([1,1,1])
transformed_point = demons_transform.TransformPoint(pointi)
diff = transformed_point-pointi
while diff[0] != 0 :
    pointi = pointi + np.array([1,0,0])
    if pointi[0]%1000 <1:
        print(pointi)
    transformed_point = demons_transform.TransformPoint(pointi)
    diff = transformed_point-pointi
pointi[0] = pointi[0]-1
diff=[1,1,1]
while diff[1] != 0 :
    pointi = pointi + np.array([0,1,0])
    if pointi[1]%1000 <1:
        print(pointi)
    transformed_point = demons_transform.TransformPoint(pointi)
    diff = transformed_point-pointi
pointi[1] = pointi[1]-1
diff=[1,1,1]
while diff[2] != 0 :
    pointi = pointi + np.array([0,0,1])
    if pointi[2]%1000 <1:
        print(pointi)
    transformed_point = demons_transform.TransformPoint(pointi)
    diff = transformed_point-pointi
print(pointi)

[1000.2   27.    41. ]
[2000.2   27.    41. ]
[3000.2   27.    41. ]
[4000.2   27.    41. ]
[5000.2   27.    41. ]
[6000.2   27.    41. ]
[7000.2   27.    41. ]
[8000.2   27.    41. ]
[9000.2   27.    41. ]
[10000.2    27.     41. ]
[11000.2    27.     41. ]
[12000.2    27.     41. ]
[13000.2    27.     41. ]
[14000.2    27.     41. ]
[15000.2    27.     41. ]
[16000.2    27.     41. ]
[17000.2    27.     41. ]
[18000.2    27.     41. ]
[18085.2  1000.     41. ]
[18085.2  2000.     41. ]
[18085.2  3000.     41. ]
[18085.2  4000.     41. ]
[18085.2  5000.     41. ]
[18085.2  6000.     41. ]
[18085.2  7000.     41. ]
[18085.2  8000.     41. ]
[18085.2  9000.     41. ]
[18085.2 10000.     41. ]
[18085.2 10883.   1000. ]
[18085.2 10883.   2000. ]
[18085.2 10883.   3000. ]
[18085.2 10883.   4000. ]
[18085.2 10883.   5000. ]
[18085.2 10883.   6000. ]
[18085.2 10883.   7000. ]
[18085.2 10883.   8000. ]
[18085.2 10883.   9000. ]
[18085.2 10883.   9320. ]


In [61]:
scale*size

array([18096. , 10899.2,  9360. ])