In [1]:
import sys
sys.path.append('/home/zhw272/programming/pipeline_utility')
from toolbox.sitk.registration_method_util import *
from notebooks.Will.toolbox.sitk.utility import get_fixed_and_moving_image
import json
import numpy as np
from notebooks.Will.toolbox.coordinate_transforms import atlas_to_thumbnail_coord
from notebooks.Will.toolbox.atlas.get_volumn_and_origin import get_origin_and_volumn
from notebooks.Will.toolbox.data_base.sql_tools import get_atlas_centers

In [10]:
def get_DK52_com():
    with open('/home/zhw272/programming/pipeline_utility/notebooks/Bili/data/DK52_coms_kui_detected.json', 'r') as f:
        atlas_coms = json.load(f)
    return atlas_coms

In [3]:
def get_demons_transform(braini):
    save_path = '/net/birdstore/Active_Atlas_Data/data_root/tfm'
    transform = sitk.ReadTransform(save_path + '/demons/' + braini + '_demons.tfm')
    return transform

In [4]:
def transform_atlas_com(atlas_com):
    transform = get_demons_transform(braini)
    estimated_target_coms = {}
    for name, com in atlas_com.items():
        transformed_coms[name] = transform.TransformPoint(com)
    return estimated_target_coms

In [5]:
fixed_image,moving_image = get_fixed_and_moving_image(fixed_brain = "DK52",moving_brain = 'DK39')

In [11]:
atlas_coms = get_DK52_com()
com_10N_L = atlas_coms['10N_L']

In [8]:
values = []
for valuei in atlas_coms.values():
    coord = np.array(valuei)*np.array([0.325,0.325,20])/4/np.array([10.4,10.4,20.0])
    values.append(coord)

In [12]:
com_10N_L

[45413, 16981, 216]

In [ ]:
atlas_spacing = np.array([10.0,10.0,20.0])
image_spacing = np.array([0.325,0.325,20.0])
thumbnail_spacing = np.array([10.4,10.4,20.0])
image_to_thumbnail_factor = np.array([32,32,1])

In [28]:
moving_image.__dir__()

['this',
 '__module__',
 '__doc__',
 'thisown',
 '__repr__',
 '__swig_destroy__',
 '__init__',
 'GetITKBase',
 'GetPixelID',
 'GetPixelIDValue',
 'GetPixelIDTypeAsString',
 'GetDimension',
 'GetNumberOfComponentsPerPixel',
 'GetNumberOfPixels',
 'GetOrigin',
 'SetOrigin',
 'GetSpacing',
 'SetSpacing',
 'GetDirection',
 'SetDirection',
 'TransformIndexToPhysicalPoint',
 'TransformPhysicalPointToIndex',
 'TransformPhysicalPointToContinuousIndex',
 'TransformContinuousIndexToPhysicalPoint',
 'GetSize',
 'GetWidth',
 'GetHeight',
 'GetDepth',
 'CopyInformation',
 'GetMetaDataKeys',
 'HasMetaDataKey',
 'GetMetaData',
 'SetMetaData',
 'EraseMetaData',
 '__str__',
 '__GetPixelAsInt8__',
 '__GetPixelAsUInt8__',
 '__GetPixelAsInt16__',
 '__GetPixelAsUInt16__',
 '__GetPixelAsInt32__',
 '__GetPixelAsUInt32__',
 '__GetPixelAsInt64__',
 '__GetPixelAsUInt64__',
 '__GetPixelAsFloat__',
 '__GetPixelAsDouble__',
 '__GetPixelAsVectorInt8__',
 '__GetPixelAsVectorUInt8__',
 '__GetPixelAsVectorInt16__',
 '

In [14]:
thumb_nail_size = moving_image.GetSize()
thumb_nail_size

(2031, 1125, 486)

In [23]:
transform_displacement_field_size = np.array([435,262,117])
displacement_spacing = np.array([41.6,41.6,80])
displacement_origin = np.array([32.2,26,40])

In [26]:
displacement_spacing/np.array([10.4,10.4,20])

array([4., 4., 4.])

In [15]:
transform = get_demons_transform('DK39')
print(transform)

itk::simple::Transform
 GaussianSmoothingOnUpdateDisplacementFieldTransform (0x3969a20)
   RTTI typeinfo:   itk::GaussianSmoothingOnUpdateDisplacementFieldTransform<double, 3u>
   Reference Count: 1
   Modified Time: 189881
   Debug: Off
   Object Name: 
   Observers: 
     none
   DisplacementField: 
     Image (0x3a5d340)
       RTTI typeinfo:   itk::Image<itk::Vector<double, 3u>, 3u>
       Reference Count: 3
       Modified Time: 189878
       Debug: Off
       Object Name: 
       Observers: 
         none
       Source: (none)
       Source output name: (none)
       Release Data: Off
       Data Released: False
       Global Release Data: Off
       PipelineMTime: 0
       UpdateMTime: 0
       RealTimeStamp: 0 seconds 
       LargestPossibleRegion: 
         Dimension: 3
         Index: [0, 0, 0]
         Size: [435, 262, 117]
       BufferedRegion: 
         Dimension: 3
         Index: [0, 0, 0]
         Size: [435, 262, 117]
       RequestedRegion: 
         Dimension: 3
   

In [19]:
transform.__dir__()

['this',
 '__module__',
 '__doc__',
 'thisown',
 '__repr__',
 '__swig_destroy__',
 '__init__',
 'GetITKBase',
 'GetDimension',
 'SetParameters',
 'GetParameters',
 'GetNumberOfParameters',
 'SetFixedParameters',
 'GetFixedParameters',
 'GetNumberOfFixedParameters',
 'TransformPoint',
 'TransformVector',
 'WriteTransform',
 'IsLinear',
 'SetIdentity',
 'SetInverse',
 'GetInverse',
 '__str__',
 'GetName',
 'MakeUnique',
 'GetTransformEnum',
 '__copy__',
 '__deepcopy__',
 '__setstate__',
 '__reduce_ex__',
 'Downcast',
 '__dict__',
 '__weakref__',
 '__hash__',
 '__getattribute__',
 '__setattr__',
 '__delattr__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__new__',
 '__reduce__',
 '__subclasshook__',
 '__init_subclass__',
 '__format__',
 '__sizeof__',
 '__dir__',
 '__class__']

In [61]:
values= np.array(values)
values.max(axis=0)

array([402.96875  , 210.8515625,  93.75     ])

In [62]:
transformed_values = [transform.TransformPoint(valuei) for valuei in values]

In [63]:
nstr= len(transformed_values)

In [66]:
diff = [(values[stri]-transformed_values[stri])*4*np.array([10.4,10.4,20.0]) for stri in range(nstr)]

In [67]:
diff

[array([-67.19797688, -17.49888009, -14.66620212]),
 array([-117.69691066,  -30.64918274,  -25.68769273]),
 array([-107.03980028,  -27.87398575,  -23.36172989]),
 array([-56.35003447, -14.67403258, -12.29882398]),
 array([-63.31472979, -16.48770017, -13.81892799]),
 array([-61.82843539, -16.10065033, -13.49450047]),
 array([-61.94459711, -16.13089973, -13.51985306]),
 array([-12.35794068,  -3.21810832,  -2.69718529]),
 array([-185.55500233,  -48.32005157,  -40.49845179]),
 array([-125.36588117,  -32.64628979,  -27.36172774]),
 array([-70.44439652, -18.34428914, -15.37483135]),
 array([-21.57632305,  -5.61863259,  -4.70905181]),
 array([-65.46520229, -17.04769688, -14.28825993]),
 array([-94.88802838, -24.70957834, -20.7096117 ]),
 array([-26.29451597,  -6.84729169,  -5.7388393 ]),
 array([-239.81991355,  -62.45095713,  -52.3414155 ]),
 array([0., 0., 0.]),
 array([-237.67807231,  -61.89323529,  -51.87411008]),
 array([-32.0102368 ,  -8.33575423,  -6.9865521 ]),
 array([-23.35747755,  -

In [24]:
np.array(atlas_com)*np.array([0.325,0.325,20])/4/10

array([368.980625, 137.970625, 108.      ])

In [9]:
thumbnail_com/4

array([10916.58653846,  4081.97115385,    54.        ])

In [14]:
np.array(atlas_com)*np.array([10,10,20])/np.array([0.325,0.325,20.0])/np.array([32,32,1])/4

array([10916.58653846,  4081.97115385,    54.        ])

In [23]:
(np.array(atlas_com-np.array([500,500,150])))*np.array([1,1,2])

array([44913, 16481,   132])

In [5]:
com_diff = {}
for structure in atlas_coms.keys():
    moving_com = atlas_coms[structure]
    fixed_com = estimated_target_coms[structure]
    com_diffi= np.array(moving_com)-np.array(fixed_com)
    com_diff[structure] = com_diffi