In [13]:
import sys
sys.path.append('/home/zhw272/programming/pipeline_utility')
from toolbox.sitk.registration_method_util import *
from notebooks.Will.toolbox.sitk.utility import get_fixed_and_moving_image
import json
import numpy as np
from notebooks.Will.toolbox.coordinate_transforms import atlas_to_thumbnail_coord
from notebooks.Will.toolbox.atlas.get_volumn_and_origin import get_origin_and_volumn
from notebooks.Will.toolbox.data_base.sql_tools import get_atlas_centers

In [14]:
def get_atlas_com(braini):
    with open('/home/zhw272/programming/pipeline_utility/notebooks/Bili/data/DK52_coms_kui_detected.json', 'r') as f:
        atlas_coms = json.load(f)
    return atlas_coms

In [3]:
def get_demons_transform(braini):
    save_path = '/net/birdstore/Active_Atlas_Data/data_root/tfm'
    transform = sitk.ReadTransform(save_path + '/demons/' + braini + '_demons.tfm')
    return transform

In [4]:
def transform_atlas_com(atlas_com):
    transform = get_demons_transform(braini)
    estimated_target_coms = {}
    for name, com in atlas_com.items():
        transformed_coms[name] = transform.TransformPoint(com)
    return estimated_target_coms

In [15]:
get_atlas_centers()

No histology for Atlas
No scan run for Atlas


{'10N_L': array([703.341 , 547.9286, 135.5   ]),
 '10N_R': array([703.341 , 547.9286, 164.5   ]),
 '12N': array([697.227 , 567.0988, 149.    ]),
 '3N_L': array([364.555, 391.506, 143.   ]),
 '3N_R': array([364.555, 391.506, 157.   ]),
 '4N_L': array([399.441, 396.104, 137.5  ]),
 '4N_R': array([399.441, 396.104, 162.5  ]),
 '5N_L': array([456.7992 , 502.07948,  82.     ]),
 '5N_R': array([456.7992 , 502.07948, 218.     ]),
 '6N_L': array([517.1597, 512.4922, 132.5   ]),
 '6N_R': array([517.1597, 512.4922, 167.5   ]),
 'AP': array([702.306 , 525.6525, 151.    ]),
 'Amb_L': array([612.44 , 603.826,  88.5  ]),
 'Amb_R': array([612.44 , 603.826, 211.5  ]),
 'DC_L': array([583.2885, 456.4954,  42.    ]),
 'DC_R': array([583.2885, 456.4954, 258.    ]),
 'IC': array([496.7529, 251.693 , 150.    ]),
 'LC_L': array([496.19734, 442.8079 , 108.     ]),
 'LC_R': array([496.19734, 442.8079 , 192.     ]),
 'LRt_L': array([688.194, 646.863,  94.   ]),
 'LRt_R': array([688.194, 646.863, 206.   ]),
 'P

In [3]:
origins,volumns = get_origin_and_volumn()

In [6]:
volumns.keys()

dict_keys(['10N_L', '10N_R', '12N', '3N_L', '3N_R', '4N_L', '4N_R', '5N_L', '5N_R', '6N_L', '6N_R', '7N_L', '7N_R', '7n_L', '7n_R', 'AP', 'Amb_L', 'Amb_R', 'DC_L', 'DC_R', 'IC', 'LC_L', 'LC_R', 'LRt_L', 'LRt_R', 'PBG_L', 'PBG_R', 'Pn_L', 'Pn_R', 'RtTg', 'SC', 'SNC_L', 'SNC_R', 'SNR_L', 'SNR_R', 'Sp5C_L', 'Sp5C_R', 'Sp5I_L', 'Sp5I_R', 'Sp5O_L', 'Sp5O_R', 'Tz_L', 'Tz_R', 'VCA_L', 'VCA_R', 'VCP_L', 'VCP_R', 'VLL_L', 'VLL_R'])

In [9]:
volumns['10N_L'].shape

(111, 87, 55)

In [10]:
origins['10N_L'] == origins['12N']

array([False, False, False])

In [5]:
origins

{'10N_L': array([153.91836816,  18.02326025, -49.05752672]),
 '10N_R': array([152.91836816,  24.02326025,   4.05752672]),
 '12N': array([140.42555865,  32.54898725, -41.        ]),
 '3N_L': array([-183.97207982, -123.14021395,  -44.5912844 ]),
 '3N_R': array([-181.97207982, -126.14021395,   -7.4087156 ]),
 '4N_L': array([-122.44813694, -114.83714871,  -31.51951106]),
 '4N_R': array([-123.44813694, -113.83714871,   13.51951106]),
 '5N_L': array([ -83.05035119,  -44.18323356, -157.58118521]),
 '5N_R': array([-86.05035119, -39.18323356, 106.58118521]),
 '6N_L': array([  0.45777028,  -6.1157717 , -47.09098064]),
 '6N_R': array([ 3.45777028, -2.1157717 , 23.09098064]),
 '7N_L': array([ -18.98770849,   76.72714712, -161.80292974]),
 '7N_R': array([-21.98770849,  75.72714712,  67.80292974]),
 '7n_L': array([ -65.76858808,  -22.50380136, -163.05430646]),
 '7n_R': array([-59.76858808, -12.50380136,  27.05430646]),
 'AP': array([171.5543851 ,   8.37782434, -18.        ]),
 'Amb_L': array([  81.3

In [7]:
atlas_com

[45413, 16981, 216]

In [11]:
fixed_image,moving_image = get_fixed_and_moving_image(fixed_brain = "DK52",moving_brain = 'DK39')

In [25]:
np.array((10.4, 10.4, 20.0))/4

array([2.6, 2.6, 5. ])

In [32]:
moving_image.GetDirection()

(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)

In [34]:
np.array([10.4,10.4,20.0])/np.array([0.325,0.325,20.0])

array([32., 32.,  1.])

In [28]:
moving_image.__dir__()

['this',
 '__module__',
 '__doc__',
 'thisown',
 '__repr__',
 '__swig_destroy__',
 '__init__',
 'GetITKBase',
 'GetPixelID',
 'GetPixelIDValue',
 'GetPixelIDTypeAsString',
 'GetDimension',
 'GetNumberOfComponentsPerPixel',
 'GetNumberOfPixels',
 'GetOrigin',
 'SetOrigin',
 'GetSpacing',
 'SetSpacing',
 'GetDirection',
 'SetDirection',
 'TransformIndexToPhysicalPoint',
 'TransformPhysicalPointToIndex',
 'TransformPhysicalPointToContinuousIndex',
 'TransformContinuousIndexToPhysicalPoint',
 'GetSize',
 'GetWidth',
 'GetHeight',
 'GetDepth',
 'CopyInformation',
 'GetMetaDataKeys',
 'HasMetaDataKey',
 'GetMetaData',
 'SetMetaData',
 'EraseMetaData',
 '__str__',
 '__GetPixelAsInt8__',
 '__GetPixelAsUInt8__',
 '__GetPixelAsInt16__',
 '__GetPixelAsUInt16__',
 '__GetPixelAsInt32__',
 '__GetPixelAsUInt32__',
 '__GetPixelAsInt64__',
 '__GetPixelAsUInt64__',
 '__GetPixelAsFloat__',
 '__GetPixelAsDouble__',
 '__GetPixelAsVectorInt8__',
 '__GetPixelAsVectorUInt8__',
 '__GetPixelAsVectorInt16__',
 '

In [26]:
moving_image.GetSize()

(2031, 1125, 486)

In [17]:
np.array((2031, 1125, 486))*np.array([32,32,1])

array([64992, 36000,   486])

In [22]:
np.array(moving_image.GetSize())/np.array([435, 262, 117])

array([4.66896552, 4.29389313, 4.15384615])

In [17]:
transform = get_demons_transform('DK39')
print(transform)

itk::simple::Transform
 GaussianSmoothingOnUpdateDisplacementFieldTransform (0x2084a330)
   RTTI typeinfo:   itk::GaussianSmoothingOnUpdateDisplacementFieldTransform<double, 3u>
   Reference Count: 1
   Modified Time: 189904
   Debug: Off
   Object Name: 
   Observers: 
     none
   DisplacementField: 
     Image (0x1f53df0)
       RTTI typeinfo:   itk::Image<itk::Vector<double, 3u>, 3u>
       Reference Count: 3
       Modified Time: 189901
       Debug: Off
       Object Name: 
       Observers: 
         none
       Source: (none)
       Source output name: (none)
       Release Data: Off
       Data Released: False
       Global Release Data: Off
       PipelineMTime: 0
       UpdateMTime: 0
       RealTimeStamp: 0 seconds 
       LargestPossibleRegion: 
         Dimension: 3
         Index: [0, 0, 0]
         Size: [435, 262, 117]
       BufferedRegion: 
         Dimension: 3
         Index: [0, 0, 0]
         Size: [435, 262, 117]
       RequestedRegion: 
         Dimension: 3
  

In [6]:
braini = 'DK39'
atlas_coms = get_atlas_com(braini)
atlas_com = atlas_coms['10N_L']
thumbnail_com = atlas_to_thumbnail_coord(atlas_com)
thumbnail_com

array([43666.34615385, 16327.88461538,   216.        ])

In [9]:
thumbnail_com/4

array([10916.58653846,  4081.97115385,    54.        ])

In [14]:
np.array(atlas_com)*np.array([10,10,20])/np.array([0.325,0.325,20.0])/np.array([32,32,1])/4

array([10916.58653846,  4081.97115385,    54.        ])

In [23]:
(np.array(atlas_com-np.array([500,500,150])))*np.array([1,1,2])

array([44913, 16481,   132])

In [5]:
com_diff = {}
for structure in atlas_coms.keys():
    moving_com = atlas_coms[structure]
    fixed_com = estimated_target_coms[structure]
    com_diffi= np.array(moving_com)-np.array(fixed_com)
    com_diff[structure] = com_diffi

In [29]:
np.linalg.inv(np.diag([1,2,3]))

array([[1.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])