In [1]:
import sys
sys.path.append('/home/zhw272/programming/pipeline_utility')
from toolbox.sitk.registration_method_util import *
from notebooks.Will.toolbox.sitk.utility import get_fixed_and_moving_image
import json
import numpy as np
from notebooks.Will.toolbox.coordinate_transforms import atlas_to_thumbnail_coord

In [2]:
def get_atlas_com(braini):
    with open('/home/zhw272/programming/pipeline_utility/notebooks/Bili/data/DK52_coms_kui_detected.json', 'r') as f:
        atlas_coms = json.load(f)
    return atlas_coms

In [3]:
def get_demons_transform(braini):
    save_path = '/net/birdstore/Active_Atlas_Data/data_root/tfm'
    transform = sitk.ReadTransform(save_path + '/demons/' + braini + '_demons.tfm')
    return transform

In [4]:
def transform_atlas_com(atlas_com):
    transform = get_demons_transform(braini)
    estimated_target_coms = {}
    for name, com in atlas_com.items():
        transformed_coms[name] = transform.TransformPoint(com)
    return estimated_target_coms

In [7]:
atlas_com

[45413, 16981, 216]

In [11]:
fixed_image,moving_image = get_fixed_and_moving_image(fixed_brain = "DK52",moving_brain = 'DK39')

In [25]:
np.array((10.4, 10.4, 20.0))/4

array([2.6, 2.6, 5. ])

In [32]:
moving_image.GetDirection()

(1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0)

In [34]:
np.array([10.4,10.4,20.0])/np.array([0.325,0.325,20.0])

array([32., 32.,  1.])

In [28]:
moving_image.__dir__()

['this',
 '__module__',
 '__doc__',
 'thisown',
 '__repr__',
 '__swig_destroy__',
 '__init__',
 'GetITKBase',
 'GetPixelID',
 'GetPixelIDValue',
 'GetPixelIDTypeAsString',
 'GetDimension',
 'GetNumberOfComponentsPerPixel',
 'GetNumberOfPixels',
 'GetOrigin',
 'SetOrigin',
 'GetSpacing',
 'SetSpacing',
 'GetDirection',
 'SetDirection',
 'TransformIndexToPhysicalPoint',
 'TransformPhysicalPointToIndex',
 'TransformPhysicalPointToContinuousIndex',
 'TransformContinuousIndexToPhysicalPoint',
 'GetSize',
 'GetWidth',
 'GetHeight',
 'GetDepth',
 'CopyInformation',
 'GetMetaDataKeys',
 'HasMetaDataKey',
 'GetMetaData',
 'SetMetaData',
 'EraseMetaData',
 '__str__',
 '__GetPixelAsInt8__',
 '__GetPixelAsUInt8__',
 '__GetPixelAsInt16__',
 '__GetPixelAsUInt16__',
 '__GetPixelAsInt32__',
 '__GetPixelAsUInt32__',
 '__GetPixelAsInt64__',
 '__GetPixelAsUInt64__',
 '__GetPixelAsFloat__',
 '__GetPixelAsDouble__',
 '__GetPixelAsVectorInt8__',
 '__GetPixelAsVectorUInt8__',
 '__GetPixelAsVectorInt16__',
 '

In [26]:
moving_image.GetSize()

(2031, 1125, 486)

In [22]:
np.array(moving_image.GetSize())/np.array([435, 262, 117])

array([4.66896552, 4.29389313, 4.15384615])

In [17]:
transform = get_demons_transform('DK39')
print(transform)

itk::simple::Transform
 GaussianSmoothingOnUpdateDisplacementFieldTransform (0x2084a330)
   RTTI typeinfo:   itk::GaussianSmoothingOnUpdateDisplacementFieldTransform<double, 3u>
   Reference Count: 1
   Modified Time: 189904
   Debug: Off
   Object Name: 
   Observers: 
     none
   DisplacementField: 
     Image (0x1f53df0)
       RTTI typeinfo:   itk::Image<itk::Vector<double, 3u>, 3u>
       Reference Count: 3
       Modified Time: 189901
       Debug: Off
       Object Name: 
       Observers: 
         none
       Source: (none)
       Source output name: (none)
       Release Data: Off
       Data Released: False
       Global Release Data: Off
       PipelineMTime: 0
       UpdateMTime: 0
       RealTimeStamp: 0 seconds 
       LargestPossibleRegion: 
         Dimension: 3
         Index: [0, 0, 0]
         Size: [435, 262, 117]
       BufferedRegion: 
         Dimension: 3
         Index: [0, 0, 0]
         Size: [435, 262, 117]
       RequestedRegion: 
         Dimension: 3
  

In [6]:
braini = 'DK39'
atlas_coms = get_atlas_com(braini)
atlas_com = atlas_coms['10N_L']
thumbnail_com = atlas_to_thumbnail_coord(atlas_com)
thumbnail_com

array([43666.34615385, 16327.88461538,   216.        ])

In [9]:
thumbnail_com/4

array([10916.58653846,  4081.97115385,    54.        ])

In [10]:
atlas_com

[45413, 16981, 216]

In [11]:
45413*10/0.325/32

43666.34615384615

In [5]:
com_diff = {}
for structure in atlas_coms.keys():
    moving_com = atlas_coms[structure]
    fixed_com = estimated_target_coms[structure]
    com_diffi= np.array(moving_com)-np.array(fixed_com)
    com_diff[structure] = com_diffi

In [29]:
np.linalg.inv(np.diag([1,2,3]))

array([[1.        , 0.        , 0.        ],
       [0.        , 0.5       , 0.        ],
       [0.        , 0.        , 0.33333333]])