In [8]:
import os, sys
import numpy as np

In [3]:
HOME = os.path.expanduser("~")
jobname = 'erodemaskfalse'
OUTPUT = os.path.join(HOME, 'elastix_test', jobname)

In [2]:
def parameter_elastix_parameter_file_to_dict(filename):
    d = {}
    with open(filename, 'r') as f:
        for line in f.readlines():
            if line.startswith('('):
                tokens = line[1:-2].split(' ')
                key = tokens[0]
                if len(tokens) > 2:
                    value = []
                    for v in tokens[1:]:
                        try:
                            value.append(float(v))
                        except ValueError:
                            value.append(v)
                else:
                    v = tokens[1]
                    try:
                        value = (float(v))
                    except ValueError:
                        value = v
                d[key] = value
        return d

In [14]:
filepath = os.path.join(OUTPUT, '337_to_336', 'TransformParameters.0.txt')
d = parameter_elastix_parameter_file_to_dict(filepath)

In [15]:
rot_rad, x_mm, y_mm = d['TransformParameters']
print(rot_rad, x_mm, y_mm)

0.024433 46.923577 -31.10455


In [16]:
center = np.array(d['CenterOfRotationPoint']) / np.array(d['Spacing'])
print(center)

[871.  524.5]


In [17]:
xshift = x_mm / d['Spacing'][0]
yshift = y_mm / d['Spacing'][1]
print(xshift, yshift)

46.923577 -31.10455


In [18]:
R = np.array([[np.cos(rot_rad), -np.sin(rot_rad)],
                  [np.sin(rot_rad), np.cos(rot_rad)]])
print(R.shape)
print(R)

(2, 2)
[[ 0.99970153 -0.02443057]
 [ 0.02443057  0.99970153]]


In [19]:
shift = center + (xshift, yshift) - np.dot(R, center)
print(shift)

[ 59.99737865 -52.22702771]


In [13]:
T = np.vstack([np.column_stack([R, shift]), [0, 0, 1]])
print(T.shape)
print(T)       

(3, 3)
[[  0.99815589  -0.06070266  33.31369429]
 [  0.06070266   0.99815589 -48.25214448]
 [  0.           0.           1.        ]]
