In [107]:
import numpy as np
from math import *
from superpose3d import Superpose3D
from collections import OrderedDict
import scipy

In [95]:
SCALE = (10 / 0.452)
MD589_centers = {'5N_L': [23790, 13025, 160],
                 '5N_R': [20805, 14163, 298],
                 '7n_L': [20988, 18405, 177],
                 '7n_R': [24554, 13911, 284],
                 'DC_L': [24482, 11985, 134],
                 'DC_R': [20424, 11736, 330],
                 'LC_L': [25290, 11750, 180],
                 'LC_R': [24894, 12079, 268],
                  'SC': [24226, 6401, 220]}
MD589_centers = OrderedDict(MD589_centers)
MD589_center_values = np.array(list(MD589_centers.values()), dtype=np.float32)
MD589_list = []
for value in MD589_centers.values():
    MD589_list.append((value[1] / SCALE, value[0] / SCALE, value[2]))
MD589 = np.array(MD589_list)

atlas_centers = {'5N_L': [460.53, 685.58, 155],
                 '5N_R': [460.53, 685.58, 293],
                 '7n_L': [499.04, 729.94, 172],
                 '7n_R': [499.04, 729.94, 276],
                 'DC_L': [580.29, 650.66, 130],
                 'DC_R': [580.29, 650.66, 318],
                 'LC_L': [505.55, 629.99, 182],
                 'LC_R': [505.55, 629.99, 266],
                  'SC': [376.87, 453.2, 226],
                 }
atlas_centers = OrderedDict(atlas_centers)
ATLAS = np.array(list(atlas_centers.values()), dtype=np.float32)

In [96]:
MD589

array([[ 588.73  , 1075.308 ,  160.    ],
       [ 640.1676,  940.386 ,  298.    ],
       [ 831.906 ,  948.6576,  177.    ],
       [ 628.7772, 1109.8408,  284.    ],
       [ 541.722 , 1106.5864,  134.    ],
       [ 530.4672,  923.1648,  330.    ],
       [ 531.1   , 1143.108 ,  180.    ],
       [ 545.9708, 1125.2088,  268.    ],
       [ 289.3252, 1095.0152,  220.    ]])

In [104]:
new_points = np.array([400,600,200])
RMSD, R, T, c = Superpose3D(MD589,ATLAS, None, False, False)
S = np.eye(3) 
A = np.dot(T, np.dot(S, R))
#trans = np.dot(A, new_points)
#_x = np.matrix(new_points).transpose()
#_xprime = c*R*_x + T
print(new_points, A)

[400 600 200] [-1483.39371288   -15.07889633  -550.5703539 ]


In [105]:
new_points = np.array([600,400,200])
result = Superpose3D(MD589,ATLAS, None, False, False)
R = np.matrix(result[1])              # rotation matrix
T = np.matrix(result[2]).transpose()  # translation vector (3x1 matrix)
c = result[3]                         # scalar
_x = np.matrix(new_points).transpose()
_xprime = c*R*_x + T
p = np.array(_xprime.transpose()) # convert to length 3 numpy array
print(c, p[0][0], p[0][1], p[0][2])

1.0 338.13708569938194 960.5274066889747 120.41051993846376


In [93]:
new_points = np.array([400,600,200])
result = Superpose3D(MD589,ATLAS, None, False, False)
R = np.matrix(result[1])              # rotation matrix
T = np.matrix(result[2]).transpose()  # translation vector (3x1 matrix)
c = result[3]
_x = np.matrix(new_points).transpose()
_xprime = c*R*_x + T
p = np.array(_xprime.transpose()) # convert to length 3 numpy array
print(c, p[0][0], p[0][1], p[0][2])

1.0 1014.1996324995772 487.0106831996645 164.20170055126422


In [64]:
xprime

array([[963.72783124, 607.02380337, 284.17945183]])

In [40]:
p = np.dot(A,new_points)
type(p)

numpy.float64

In [18]:
X=[[0,0,0],[0,0,1],[0,1,1],[1,1,1]]
x=[[0,0,0],[0,1.05,0],[0,1,-1],[1,1,-1]]  # (a slightly modified rotated X)


result = Superpose3D(X,x, None, False, False)
print(' (quaternion = '+str(result[1])+')\n')

Xshifted = [ [X[i][0],X[i][1]+100, X[i][2]] for i in range(0,len(X))]
xscaled  = [ [2*x[i][0],2*x[i][1],    2*x[i][2]] for i in range(0,len(x))]
xscshift = [ [2*x[i][0],2*x[i][1]+200,2*x[i][2]] for i in range(0,len(x))]

 (quaternion = [[ 9.99993156e-01 -3.59598928e-03  8.70039606e-04]
 [ 8.22214121e-04 -1.32798221e-02 -9.99911481e-01]
 [ 3.60722494e-03  9.99905353e-01 -1.32767746e-02]])



In [11]:
xscshift

[[0, 200, 0], [0, 202.1, 0], [0, 202, -2], [2, 202, -2]]

In [52]:
X=[[0,0,0],[0,0,1],[0,1,1],[1,1,1]]
x=[[0,0,0],[0,1.05,0],[0,1,-1],[1,1,-1]]  # (a slightly modified rotated X)


result = Superpose3D(X,x, None, False, True)
print(' (quaternion = '+str(result[1])+')\n')

Xshifted = [ [X[i][0],X[i][1]+100, X[i][2]] for i in range(0,len(X))]
xscaled  = [ [2*x[i][0],2*x[i][1],    2*x[i][2]] for i in range(0,len(x))]
xscshift = [ [2*x[i][0],2*x[i][1]+200,2*x[i][2]] for i in range(0,len(x))]

# Now try again using the translated, rescaled coordinates:

# now test weights, rescale, and quaternions
w = [1.0, 1.0, 1.0, 1.0]
result = Superpose3D(X, xscshift, w, True)
# Does the RMSD returned in result[0] match the RMSD calculated manually?
R = np.matrix(result[1])              # rotation matrix
T = np.matrix(result[2]).transpose()  # translation vector (3x1 matrix)
c = result[3]                         # scalar
if len(X) > 0:
    _x = np.matrix(xscshift).transpose()
    print('_x', _x)
    _xprime = c*R*_x + T
    xprime = np.array(_xprime.transpose()) # convert to length 3 numpy array
else:
    xprime = np.array([])

print('1st (frozen) point cloud:\n'+str(X))
print('2nd (mobile) point cloud:\n'+str(xscshift))
print('2nd (mobile) point cloud after scale(c), rotation(R), translation(T):\n' +
      str(xprime))
print('rmsd = '+str(result[0]))
print('scale (c) = '+str(result[3]))
print('rotation (R) = \n'+str(result[1]))
print('translation (T) = '+str(result[2]))
print('transformation used: x_i\' = Sum_over_j c*R_ij*x_j + T_i')

RMSD = 0.0
for i in range(0, len(X)):
    RMSD += ((X[i][0] - xprime[i][0])**2 +
             (X[i][1] - xprime[i][1])**2 +
             (X[i][2] - xprime[i][2])**2)

if len(X) > 0:
    RMSD = sqrt(RMSD / len(X))

assert(abs(RMSD - result[0]) < 1.0e-6)


 (quaternion = [ 0.70239529  0.71178469 -0.00097423  0.00157255])

_x [[  0.    0.    0.    2. ]
 [200.  202.1 202.  202. ]
 [  0.    0.   -2.   -2. ]]
1st (frozen) point cloud:
[[0, 0, 0], [0, 0, 1], [0, 1, 1], [1, 1, 1]]
2nd (mobile) point cloud:
[[0, 200, 0], [0, 202.1, 0], [0, 202, -2], [2, 202, -2]]
2nd (mobile) point cloud after scale(c), rotation(R), translation(T):
[[-0.04671682 -0.0890972  -0.1756188 ]
 [-0.05125589 -0.10585979  1.0865216 ]
 [-0.05208566  1.09698428  1.04238038]
 [ 1.15005837  1.09797271  1.04671682]]
rmsd = [0.16620452]
scale (c) = 0.601076131135872
rotation (R) = 
[[ 9.99993156e-01 -3.59598928e-03  8.70039606e-04]
 [ 8.22214121e-04 -1.32798221e-02 -9.99911481e-01]
 [ 3.60722494e-03  9.99905353e-01 -1.32767746e-02]]
translation (T) = [   0.38557585    1.50733962 -120.37946703]
transformation used: x_i' = Sum_over_j c*R_ij*x_j + T_i


In [111]:
from scipy.ndimage import affine_transform
arr=
c_in=0.5*array(src.shape)
c_out=array((256.0,256.0))

angle=10/180*np.pi
c=np.cos(angle)
s=np.sin(angle)
mat=np.array([[c,-s,0,0],[s,c,0,0],[0,0,1,0],[0,0,0,1]])
output=affine_transform(arr,mat,order=2,offset=offset,output_shape=(512,512),cval=0.0,output=float32)


NameError: name 'offset' is not defined